services:
  postgres:
    image: postgres:17
    container_name: verys-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: verys
      POSTGRES_PASSWORD: verys
      POSTGRES_DB: verys
    volumes:
      - pgdata:/var/lib/postgresql/data

  verys:
    build:
      context: .
      args:
        ENV: dev
    container_name: verys-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://verys:verys@postgres:5432/verys
      USERNAME_SMTP: ${USERNAME_SMTP}
      PASSWORD_SMTP: ${PASSWORD_SMTP}
      JWT_PRIVATE_KEY: ${JWT_PRIVATE_KEY}
      OPENOBSERVE_ENDPOINT: ${OPENOBSERVE_ENDPOINT}
      OPENOBSERVE_USER: ${OPENOBSERVE_USER}
      OPENOBSERVE_TOKEN: ${OPENOBSERVE_TOKEN}
      VERYS_CLIENT_ID: ${VERYS_CLIENT_ID}
      VERYS_CLIENT_REDIRECT_URI: ${VERYS_CLIENT_REDIRECT_URI}
      VERYS_CLIENT_REGISTRATION_URI: ${VERYS_CLIENT_REGISTRATION_URI}
volumes:
  pgdata:
