services:
  postgres:
    image: postgres:17
    container_name: sso-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: sso
      POSTGRES_PASSWORD: sso
      POSTGRES_DB: sso
    volumes:
      - pgdata:/var/lib/postgresql/data

  sso:
    build:
      context: .
      args:
        ENV: dev
    container_name: sso-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://sso:sso@postgres:5432/sso
      USERNAME_SMTP: ${USERNAME_SMTP}
      PASSWORD_SMTP: ${PASSWORD_SMTP}
      JWT_PRIVATE_KEY: ${JWT_PRIVATE_KEY}
      OPENOBSERVE_ENDPOINT: ${OPENOBSERVE_ENDPOINT}
      OPENOBSERVE_USER: ${OPENOBSERVE_USER}
      OPENOBSERVE_TOKEN: ${OPENOBSERVE_TOKEN}

volumes:
  pgdata:
